# Library Demo

## Asset Module

### Instantiating an Asset object

In [1]:
from assets import Asset

# create an Asset object just by passing a ticker
btc = Asset('BTC-USD')
print(btc.asset_type, btc.currency, btc.timezone)
btc.daily.head()

Cryptocurrency USD UTC

,open,high,low,close,adj_close,volume,log_rets,rets
date,,,,,,,,
2020-01-01,7194.89209,7254.33057,7174.94434,7200.17432,7200.17432,1.856566e+10,NaN,NaN
2020-01-02,7202.55127,7212.15527,6935.27002,6985.47021,6985.47021,2.080208e+10,-0.030273,-0.029819
2020-01-03,6984.42871,7413.71533,6914.99609,7344.88428,7344.88428,2.811148e+10,0.050172,0.051452
2020-01-04,7345.37549,7427.38574,7309.51416,7410.65674,7410.65674,1.844427e+10,0.008915,0.008955
2020-01-05,7410.45166,7544.49707,7400.53564,7411.31738,7411.31738,1.972507e+10,0.000089,0.000089

### Creating various plots

In [2]:
btc.plot_price_history(start_date='2024');

In [3]:
# use different granularity
from datetime import datetime, timedelta
import pandas as pd

start_date = pd.to_datetime(datetime.now() - timedelta(days=5)).tz_localize('UTC').tz_convert(btc.timezone)
btc.plot_candlestick(timeframe='5m', start_date=start_date);

In [4]:
btc.plot_SMA(window=20, bollinger_bands=True);

In [5]:
btc.plot_returns_dist();

### Basic statistical analysis

In [6]:
# returns, price and distribution statistics
btc.stats

{'returns': {'total_return': 12.356863030782844,
  'daily_mean': 0.0019482651731325795,
  'daily_std': 0.03328475604075658,
  'daily_median': 0.0006236599301214785,
  'annualized_vol': 0.5283791215997806},
 'price': {'high': 109114.88281,
  'low': 4106.98096,
  '52w_high': 109114.88281,
  '52w_low': 105291.73438,
  'current': 96171.74219},
 'distribution': {'skewness': -0.5164410468831315,
  'kurtosis': 11.235742338476243}}

In [7]:
# get rolling statistics based on specified parameters
btc.rolling_stats(ewm=True, alpha=0.2, sharpe_ratio=True)

,close_mean,close_std,adj_close_mean,adj_close_std,rets_mean,rets_std,log_rets_mean,log_rets_std,sharpe
date,,,,,,,,,
2020-01-03,7189.086890,189.603706,7189.086890,189.603706,0.015331,0.057467,0.014419,0.056883,4.235036
2020-01-04,7264.144428,190.219808,7264.144428,190.219808,0.012718,0.038507,0.012163,0.038069,5.243021
2020-01-05,7307.925054,172.410145,7307.925054,172.410145,0.008440,0.030392,0.008073,0.029996,4.408317
2020-01-06,7432.961426,269.802450,7432.961426,269.802450,0.020295,0.032187,0.019701,0.031686,10.009410
2020-01-07,7617.889936,417.949760,7617.889936,417.949760,0.028556,0.030894,0.027785,0.030370,14.673427
...,...,...,...,...,...,...,...,...,...
2025-02-13,97311.048557,1887.488183,97311.048557,1887.488183,-0.001890,0.017428,-0.002027,0.017410,-1.721440
2025-02-14,97328.591972,1688.630890,97328.591972,1688.630890,0.000331,0.016284,0.000213,0.016280,0.322210
2025-02-15,97378.943889,1514.129567,97378.943889,1514.129567,0.000637,0.014579,0.000543,0.014578,0.693900
2025-02-16,97254.861361,1379.621256,97254.861361,1379.621256,-0.001175,0.013595,-0.001257,0.013587,-1.371522
2025-02-17,97038.237527,1316.757507,97038.237527,1316.757507,-0.002153,0.012335,-0.002223,0.012324,-2.770143

In [8]:
# get resampled data
btc.resample('ME')

,open,high,low,close,adj_close,volume,log_rets,rets
date,,,,,,,,
2020-02-29,9346.35742,10457.62695,8492.93262,8599.50879,8599.50879,1.163376e+12,-0.083728,-0.080319
2020-03-31,8599.75879,9167.69531,4106.98096,6438.64453,6438.64453,1.290442e+12,-0.289387,-0.251278
2020-04-30,6437.31934,9440.65039,6202.37354,8658.55371,8658.55371,1.156127e+12,0.296230,0.344779
2020-05-31,8672.78223,9996.74316,8374.32324,9461.05859,9461.05859,1.286368e+12,0.088637,0.092683
2020-06-30,9463.60547,10199.56543,8975.52539,9137.99316,9137.99316,6.509133e+11,-0.034743,-0.034147
...,...,...,...,...,...,...,...,...
2024-10-31,63335.60547,73577.21094,58895.20703,70215.18750,70215.18750,9.937324e+11,0.103213,0.108728
2024-11-30,70216.89844,99655.50000,66803.64844,96449.05469,96449.05469,2.055809e+12,0.317450,0.373621
2024-12-31,96461.33594,108268.44531,91317.13281,93429.20313,93429.20313,2.057356e+12,-0.031811,-0.031310
2025-01-31,93425.10156,109114.88281,89260.10156,102405.02344,102405.02344,1.668843e+12,0.091732,0.096071
2025-02-28,102402.79688,102755.72656,91242.89063,96171.74219,96171.74219,7.366389e+11,-0.062800,-0.060869

## Strategy Module

### Technical Analysis Engine

In [9]:
from strategy import TAEngine
ta = TAEngine()

# calculate various technical indicators using the TA engine
ta.calculate_macd(btc.daily['adj_close'], [12, 26, 9], 'demo_macd')

                   macd  signal_line   macd_hist
date
2020-01-01     0.000000     0.000000    0.000000
2020-01-02    -4.817079    -2.676155    2.140924
2020-01-03     5.007494     0.472881   -4.534612
2020-01-04    11.727871     4.285547   -7.442324
2020-01-05    15.159010     7.520156   -7.638854
...                 ...          ...         ...
2025-02-13 -1029.672429  -623.841910  405.830519
2025-02-14  -978.745968  -694.822721  283.923247
2025-02-15  -913.207033  -738.499584  174.707449
2025-02-16  -917.010261  -774.201719  142.808542
2025-02-17  -956.349123  -810.631200  145.717923

[1875 rows x 3 columns]

### Strategy classes

In [10]:
from strategy import MA_Crossover, RSI, BB, MACD, CombinedStrategy

# create trading strategies for an asset based on technical indicators and plot the technical indicators
ma_crossover = MA_Crossover(btc, long_window=100)
ma_crossover.plot();

In [11]:
# backtest strategies
rsi = RSI(btc, signal_type=['divergence', 'crossover'])
rsi.backtest()

returns     11.808626
strategy     4.788710
dtype: float64

In [12]:
# optimize parameters with parallel grid search
bb = BB(btc)
bb.optimize(inplace=True)
bb.backtest()

returns      9.482526
strategy    17.755115
dtype: float64

In [13]:
# or optimize weights between different signals
macd = MACD(btc)
macd.optimize(inplace=True)
macd.backtest()

returns     13.356863
strategy    24.453094
dtype: float64

In [14]:
ma_crossover.plot(), rsi.plot(), bb.plot(), macd.plot();

In [15]:
# combine the individual strategies
combine = CombinedStrategy(btc, [ma_crossover, rsi, bb, macd])

# optimize and backtest using different timeframes
combine.optimize_weights(inplace=True, timeframe='5m', end_date='01-01-2025')
combine.backtest(start_date='01-01-2025')

returns     1.029354
strategy    0.971483
dtype: float64

## Signal Generation Module

In [16]:
import signal_gen as sg

# calculate technical indicators using engine first
df = btc.daily.copy()
df['short_ma'] = ta.calculate_ma(df['adj_close'], param_type='window', param=50, ewm=False, name='demo_ma')
df['long_ma'] = ta.calculate_ma(df['adj_close'], param_type='window', param=252, ewm=False, name='demo_ma')
df['rsi'] = ta.calculate_rsi(df['adj_close'], 14, name='demo_rsi')
df[['sma', 'bol_up', 'bol_low']] = ta.calculate_bb(df['adj_close'], 20, 2, 'demo_bb')

# this is not recalculated since it has been cached in the earlier calculation
df[['macd', 'signal_line', 'macd_hist']] = ta.calculate_macd(df['adj_close'], [12, 26, 9], 'demo_macd')
df.dropna(inplace=True)
df.head()

,open,high,low,close,adj_close,volume,log_rets,rets,short_ma,long_ma,rsi,sma,bol_up,bol_low,macd,signal_line,macd_hist
date,,,,,,,,,,,,,,,,,
2020-09-08,10369.30664,10414.77539,9945.11035,10131.51660,10131.51660,3.343093e+10,-0.023224,-0.022956,11187.123653,9065.604767,35.768906,11215.216944,12511.496415,9918.937473,-289.555420,-104.564946,184.990474
2020-09-09,10134.15137,10350.54297,10017.25098,10242.34766,10242.34766,2.412829e+10,0.010880,0.010939,11204.472852,9077.676884,37.872681,11133.415723,12459.628245,9807.203202,-310.142690,-145.680495,164.462195
2020-09-10,10242.33008,10503.91211,10238.13574,10363.13867,10363.13867,5.440644e+10,0.011724,0.011793,11221.228360,9091.080330,40.172597,11071.948194,12422.308881,9721.587507,-313.102177,-179.164831,133.937346
2020-09-11,10369.02832,10434.92285,10140.83691,10400.91504,10400.91504,4.520112e+10,0.003639,0.003645,11237.625215,9103.207436,40.909344,11007.902686,12357.974842,9657.830530,-308.839248,-205.099715,103.739534
2020-09-12,10409.86133,10578.83789,10292.38672,10442.17090,10442.17090,3.675008e+10,0.003959,0.003967,11255.730782,9115.237254,41.752956,10946.768848,12282.238744,9611.298952,-298.688746,-223.817521,74.871225

In [17]:
# generate signals based on common patterns

# MA
sg.ma_crossover(df['short_ma'], df['long_ma'])

# RSI
sg.rsi_crossover(df['rsi'], ub=70, lb=30, exit='re', m_rev_bound=50)
sg.rsi_divergence(df['rsi'], df['adj_close'])
sg.rsi_divergence(df['rsi'], df['adj_close'], hidden=True)

# BB
sg.bb_breakout(df['adj_close'], df['bol_up'], df['bol_low'])
sg.bb_walks(df['adj_close'], df['bol_up'], df['bol_low'])
sg.bb_bounce(df['adj_close'], df['bol_up'], df['bol_low'])
sg.bb_double(df['adj_close'], df['bol_up'], df['bol_low'])
sg.bb_breakout(df['adj_close'], df['bol_up'], df['bol_low'])
sg.bb_pctB(df['adj_close'], df['bol_up'], df['bol_low'])

# MACD
sg.macd_divergence(df['macd'], df['adj_close'])
sg.macd_divergence(df['macd'], df['adj_close'], hidden=True)
sg.macd_double(df['macd_hist'])
sg.macd_momentum(df['macd_hist']);